#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "aoc.h"
#include "file4c.h"
#include "string4c.h"
#include "testing/assertions.h"

// Find the nth term in the look and say sequence.
// The nth term is generated by reading the (n-1)th term.
char *look_and_say(char* input) {
    size_t length = strlen(input);
    string_buffer_t *sb = string_buffer_create(length * 2);

    for(size_t i = 0; i < length; i++) {
        // We're currently looking at the first occurrence of a digit in the input string.
        size_t occurrences = 1;
        // Look ahead at the next digit to see if it's the same.
        while (i < length - 1 && input[i] == input[i + 1]) {
            // Move to the next digit.
            i += 1;
            occurrences += 1;
        }
        char temp[1024];
        sprintf(temp, "%zu%c", occurrences, input[i]);
        string_buffer_append(sb, temp);
    }
   
    char *result = malloc(sb->length + 1);
    strcpy(result, sb->content);
    result[sb->length] = '\0';
    string_buffer_destroy(sb);
    return result;
}

void test_look_and_say(char* input, char* expected_result) {
    // assign, act
    char *result = look_and_say(input);

    // assert
    assert_string_equality(expected_result, result, "look_and_say(\"%s\") != %s (%s)\n", input, expected_result, result);
    printf("%s(\"%s\", \"%s\") passed\n", __func__, input, expected_result);
    free(result);
}

int main(int argc, char* argv[]) {
    (void)argc;
    
    test_look_and_say("1", "11");
    test_look_and_say("11", "21");
    test_look_and_say("21", "1211");
    test_look_and_say("1211", "111221");

    solution_t *solution = solution_create(2015, 10);
    char *file_content = file_read_all_text(argv[1]);

    for(int i = 0; i < 50; i++)
    {
        if(i == 40) {
            solution_part_finalize_with_ui(solution, 0, strlen(file_content), "360154");
        }

        char *next_sequence = look_and_say(file_content);
        // Free the memory held by file_content and point file_content to new memory allocated for next_sequence.
        free(file_content);
        file_content = next_sequence;
    }
    solution_part_finalize_with_ui(solution, 1, strlen(file_content), "5103798");

    free(file_content);
    return solution_finalize_and_destroy(solution);
}
